version: '3'

services:
    game_process_calculator:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: game_process_calculator
        restart: always
        command: bash etc/entrypoint.sh
        volumes:
            - .:/usr/src
        ports:
            - 8203:8000
        environment:
            - LOGICAL_ENV=${LOGICAL_ENV}
            - SERVICE_URL=${GAME_PROCESS_CALCULATOR_SERVICE_URL}
